package stellar

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// StellarConfigFile represents the local version-controlled configuration
// file (.devex.stellar.yaml) storing project funding split proposals
// for the Stellar network.
type StellarConfigFile struct {
	// AccountID is the Stellar public key of the project.
	AccountID string `yaml:"account_id" json:"account_id"`

	// Network is "testnet" or "mainnet".
	Network string `yaml:"network" json:"network"`

	// Splits is the list of configured dependency split allocations.
	Splits []StellarSplitConfig `yaml:"splits" json:"splits"`
}

// StellarSplitConfig represents a single dependency's allocation in .devex.stellar.yaml.
type StellarSplitConfig struct {
	// DependencyName is the fully-qualified package name.
	DependencyName string `yaml:"dependency_name" json:"dependency_name"`

	// StellarAddress is the Stellar public key of the recipient (G...).
	StellarAddress string `yaml:"stellar_address,omitempty" json:"stellar_address,omitempty"`

	// Percentage is the allocated split percentage (0-100).
	Percentage int `yaml:"percentage" json:"percentage"`

	// Locked prevents future auto-generations from overwriting this entry.
	Locked bool `yaml:"locked,omitempty" json:"locked,omitempty"`
}

// LoadStellarConfig reads and unmarshals a StellarConfigFile from YAML.
func LoadStellarConfig(path string) (*StellarConfigFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading stellar config %s: %w", path, err)
	}

	var cfg StellarConfigFile
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing stellar config %s: %w", path, err)
	}

	return &cfg, nil
}

// SaveStellarConfig marshals and writes a StellarConfigFile to YAML with a helpful header.
func SaveStellarConfig(path string, cfg *StellarConfigFile) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshalling stellar config: %w", err)
	}

	header := []byte("# DevEx Stellar Funding Configuration (.devex.stellar.yaml)\n" +
		"# Generated by 'devex funding generate --network stellar'\n" +
		"# You may manually edit percentages or set 'locked: true' on entries to prevent overwriting.\n\n")

	if err := os.WriteFile(path, append(header, data...), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}

	return nil
}

// MergeStellarConfig merges a newly generated StellarConfigFile with an existing one.
// Any entry in existing that has Locked set to true is preserved exactly,
// and the remaining percentage budget is distributed among unlocked newly generated entries.
func MergeStellarConfig(existing, newlyGenerated *StellarConfigFile) *StellarConfigFile {
	if existing == nil {
		return newlyGenerated
	}

	merged := &StellarConfigFile{
		AccountID: newlyGenerated.AccountID,
		Network:   newlyGenerated.Network,
	}
	if merged.AccountID == "" {
		merged.AccountID = existing.AccountID
	}
	if merged.Network == "" {
		merged.Network = existing.Network
	}

	// Collect locked entries from existing config.
	lockedMap := make(map[string]StellarSplitConfig)
	lockedBudget := 0
	for _, sp := range existing.Splits {
		if sp.Locked {
			lockedMap[sp.DependencyName] = sp
			lockedBudget += sp.Percentage
		}
	}

	// If no entries are locked, return newly generated config preserving AccountID if needed.
	if len(lockedMap) == 0 {
		return newlyGenerated
	}

	remainingBudget := 100 - lockedBudget
	if remainingBudget < 0 {
		remainingBudget = 0
	}

	// Sum percentages of unlocked entries in newlyGenerated.
	unlockedSum := 0
	var unlockedEntries []StellarSplitConfig
	for _, sp := range newlyGenerated.Splits {
		if _, isLocked := lockedMap[sp.DependencyName]; !isLocked {
			unlockedEntries = append(unlockedEntries, sp)
			unlockedSum += sp.Percentage
		}
	}

	// Build merged splits list.
	// First include locked entries in their original order from existing.
	for _, sp := range existing.Splits {
		if sp.Locked {
			merged.Splits = append(merged.Splits, sp)
		}
	}

	// Scale and append unlocked entries.
	if len(unlockedEntries) > 0 && unlockedSum > 0 && remainingBudget > 0 {
		scale := float64(remainingBudget) / float64(unlockedSum)
		newTotal := lockedBudget
		for i := range unlockedEntries {
			unlockedEntries[i].Percentage = int(float64(unlockedEntries[i].Percentage) * scale)
			newTotal += unlockedEntries[i].Percentage
		}

		// Allocate rounding remainder to the first unlocked entry with > 0 percentage.
		remainder := 100 - newTotal
		for i := range unlockedEntries {
			if remainder <= 0 {
				break
			}
			if unlockedEntries[i].Percentage > 0 {
				unlockedEntries[i].Percentage += remainder
				break
			}
		}

		merged.Splits = append(merged.Splits, unlockedEntries...)
	}

	return merged
}
