package drips

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// DripsConfigFile represents the local version-controlled configuration
// file (.devex.drips.yaml) storing project funding split proposals.
type DripsConfigFile struct {
	// ProjectID is the Drips Account ID or Ethereum address of the project.
	ProjectID string `yaml:"project_id" json:"project_id"`

	// Splits is the list of configured dependency split allocations.
	Splits []SplitConfig `yaml:"splits" json:"splits"`
}

// SplitConfig represents a single dependency's allocation in .devex.drips.yaml.
type SplitConfig struct {
	// DependencyName is the fully-qualified package name.
	DependencyName string `yaml:"dependency_name" json:"dependency_name"`

	// DripsAccountID is the resolved Drips Account ID (e.g. "drips:1:cobra").
	DripsAccountID string `yaml:"drips_account_id,omitempty" json:"drips_account_id,omitempty"`

	// Address is the Ethereum address of the recipient.
	Address string `yaml:"address,omitempty" json:"address,omitempty"`

	// Percentage is the allocated split percentage (0-100).
	Percentage int `yaml:"percentage" json:"percentage"`

	// Locked prevents future auto-generations from overwriting this entry.
	Locked bool `yaml:"locked,omitempty" json:"locked,omitempty"`
}

// LoadDripsConfig reads and unmarshals a DripsConfigFile from YAML.
func LoadDripsConfig(path string) (*DripsConfigFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading drips config %s: %w", path, err)
	}

	var cfg DripsConfigFile
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing drips config %s: %w", path, err)
	}

	return &cfg, nil
}

// SaveDripsConfig marshals and writes a DripsConfigFile to YAML with a helpful header.
func SaveDripsConfig(path string, cfg *DripsConfigFile) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshalling drips config: %w", err)
	}

	header := []byte("# DevEx Drips Funding Configuration (.devex.drips.yaml)\n" +
		"# Generated by 'devex funding generate'\n" +
		"# You may manually edit percentages or set 'locked: true' on entries to prevent overwriting.\n\n")

	if err := os.WriteFile(path, append(header, data...), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}

	return nil
}

// MergeDripsConfig merges a newly generated DripsConfigFile with an existing one.
// Any entry in existing that has Locked set to true is preserved exactly,
// and the remaining percentage budget is distributed among unlocked newly generated entries.
func MergeDripsConfig(existing, newlyGenerated *DripsConfigFile) *DripsConfigFile {
	if existing == nil {
		return newlyGenerated
	}

	merged := &DripsConfigFile{
		ProjectID: newlyGenerated.ProjectID,
	}
	if merged.ProjectID == "" {
		merged.ProjectID = existing.ProjectID
	}

	// Collect locked entries from existing config.
	lockedMap := make(map[string]SplitConfig)
	lockedBudget := 0
	for _, sp := range existing.Splits {
		if sp.Locked {
			lockedMap[sp.DependencyName] = sp
			lockedBudget += sp.Percentage
		}
	}

	// If no entries are locked, return newly generated config preserving ProjectID if needed.
	if len(lockedMap) == 0 {
		return newlyGenerated
	}

	remainingBudget := 100 - lockedBudget
	if remainingBudget < 0 {
		remainingBudget = 0
	}

	// Sum percentages of unlocked entries in newlyGenerated.
	unlockedSum := 0
	var unlockedEntries []SplitConfig
	for _, sp := range newlyGenerated.Splits {
		if _, isLocked := lockedMap[sp.DependencyName]; !isLocked {
			unlockedEntries = append(unlockedEntries, sp)
			unlockedSum += sp.Percentage
		}
	}

	// Build merged splits list.
	// First include locked entries in their original order from existing.
	for _, sp := range existing.Splits {
		if sp.Locked {
			merged.Splits = append(merged.Splits, sp)
		}
	}

	// Scale and append unlocked entries.
	if len(unlockedEntries) > 0 && unlockedSum > 0 && remainingBudget > 0 {
		scale := float64(remainingBudget) / float64(unlockedSum)
		newTotal := lockedBudget
		for i := range unlockedEntries {
			unlockedEntries[i].Percentage = int(float64(unlockedEntries[i].Percentage) * scale)
			newTotal += unlockedEntries[i].Percentage
		}

		// Allocate rounding remainder to the first unlocked entry with > 0 percentage.
		remainder := 100 - newTotal
		for i := range unlockedEntries {
			if remainder <= 0 {
				break
			}
			if unlockedEntries[i].Percentage > 0 {
				unlockedEntries[i].Percentage += remainder
				break
			}
		}

		merged.Splits = append(merged.Splits, unlockedEntries...)
	}

	return merged
}
