package cmd

import (
	"fmt"
	"io"

	"github.com/BCPathway/devex-cli/pkg/drips"
	"github.com/BCPathway/devex-cli/pkg/stellar"
)

// MarkdownFormatter renders output as GitHub-Flavored Markdown.
type MarkdownFormatter struct{}

func (f *MarkdownFormatter) Format(w io.Writer, data any) error {
	switch d := data.(type) {
	case InspectOutput:
		f.renderDripsInspect(w, d)
	case []StellarRecipientRow:
		f.renderStellarInspect(w, d)
	case *drips.SplitsDiff:
		f.renderDripsDiff(w, d)
	case *stellar.StellarSplitsDiff:
		f.renderStellarDiff(w, d)
	default:
		// Fallback for commands that do not support markdown output yet
		fmt.Fprintf(w, "Markdown output not natively supported for this command. Raw data:\n%+v\n", d)
	}
	return nil
}

func (f *MarkdownFormatter) renderDripsInspect(w io.Writer, output InspectOutput) {
	fmt.Fprintf(w, "**🔍 Drips Dependency Audit: %d packages scanned. %d%% total allocation.**\n\n", output.TotalScanned, output.Summary.TotalSplitPct)

	useDetails := len(output.Recipients) > 10
	if useDetails {
		fmt.Fprintln(w, "<details><summary>View full dependency list</summary>")
		fmt.Fprintln(w, "")
	}

	fmt.Fprintln(w, "| Dependency | Version | Status | Split % | Address |")
	fmt.Fprintln(w, "| :--- | :--- | :---: | :---: | :--- |")

	for _, r := range output.Recipients {
		statusStr := statusToEmoji(r.Status)
		splitStr := "—"
		if r.RecommendedSplitPct > 0 {
			splitStr = fmt.Sprintf("%d%%", r.RecommendedSplitPct)
		}
		addrStr := "`" + r.Address + "`"
		if r.Address == "" {
			addrStr = "—"
		}
		fmt.Fprintf(w, "| `%s` | `%s` | %s | %s | %s |\n",
			r.DependencyName, r.Version, statusStr, splitStr, addrStr)
	}

	if useDetails {
		fmt.Fprintln(w, "\n</details>")
	}

	fmt.Fprintln(w, "\n---")
	fmt.Fprintln(w, "_Generated by [devex-cli](https://github.com/BCPathway/devex-cli) • Run `devex funding sync` to apply on-chain._")
	fmt.Fprintln(w, "")
}

func (f *MarkdownFormatter) renderStellarInspect(w io.Writer, rows []StellarRecipientRow) {
	fmt.Fprintf(w, "**🔍 Stellar Dependency Audit: %d packages scanned. 100%% total allocation.**\n\n", len(rows))

	useDetails := len(rows) > 10
	if useDetails {
		fmt.Fprintln(w, "<details><summary>View full dependency list</summary>")
		fmt.Fprintln(w, "")
	}

	fmt.Fprintln(w, "| Dependency | Version | Status | Split % | Stellar Address |")
	fmt.Fprintln(w, "| :--- | :--- | :---: | :---: | :--- |")

	for _, r := range rows {
		fmt.Fprintf(w, "| `%s` | `%s` | ⬜ | %d%% | — |\n",
			r.Name, r.Version, r.Pct)
	}

	if useDetails {
		fmt.Fprintln(w, "\n</details>")
	}

	fmt.Fprintln(w, "\n---")
	fmt.Fprintln(w, "_Generated by [devex-cli](https://github.com/BCPathway/devex-cli) • Run `devex funding generate --network stellar` to create config._")
	fmt.Fprintln(w, "")
}

func (f *MarkdownFormatter) renderDripsDiff(w io.Writer, diff *drips.SplitsDiff) {
	fmt.Fprintf(w, "**🔄 Drips Splits Diff: %d changes proposed.**\n\n", diff.AddedCount+diff.RemovedCount+diff.ModifiedCount)

	if len(diff.Items) == 0 {
		fmt.Fprintln(w, "*(No splits found in local config or on-chain)*")
		fmt.Fprintln(w, "")
		return
	}

	fmt.Fprintln(w, "| Status | Dependency / Receiver | Old % | New % |")
	fmt.Fprintln(w, "| :---: | :--- | :---: | :---: |")

	for _, item := range diff.Items {
		name := fmt.Sprintf("`%s`", item.Identifier)
		switch item.Type {
		case drips.DiffAdded:
			fmt.Fprintf(w, "| 🟢 ADDED | %s | — | %d%% |\n", name, item.NewPercentage)
		case drips.DiffRemoved:
			fmt.Fprintf(w, "| 🔴 REMOVED | %s | %d%% | — |\n", name, item.OldPercentage)
		case drips.DiffModified:
			fmt.Fprintf(w, "| 🟡 MODIFIED | %s | %d%% | %d%% |\n", name, item.OldPercentage, item.NewPercentage)
		case drips.DiffUnchanged:
			fmt.Fprintf(w, "| ⚪ UNCHANGED | %s | %d%% | %d%% |\n", name, item.OldPercentage, item.OldPercentage)
		}
	}

	fmt.Fprintln(w, "\n**Net Change:**")
	fmt.Fprintf(w, "- 🟢 %d dependencies added\n", diff.AddedCount)
	fmt.Fprintf(w, "- 🔴 %d dependencies removed\n", diff.RemovedCount)
	fmt.Fprintf(w, "- 🟡 %d dependencies modified\n", diff.ModifiedCount)

	fmt.Fprintln(w, "\n---")
	fmt.Fprintln(w, "_Generated by [devex-cli](https://github.com/BCPathway/devex-cli) • Run `devex funding sync` to apply on-chain._")
	fmt.Fprintln(w, "")
}

func (f *MarkdownFormatter) renderStellarDiff(w io.Writer, diff *stellar.StellarSplitsDiff) {
	fmt.Fprintf(w, "**🔄 Stellar Splits Diff: %d changes proposed.**\n\n", diff.AddedCount+diff.RemovedCount+diff.ModifiedCount)

	if len(diff.Items) == 0 {
		fmt.Fprintln(w, "*(No splits found in local config or payment history)*")
		fmt.Fprintln(w, "")
		return
	}

	fmt.Fprintln(w, "| Status | Dependency / Receiver | Old % | New % |")
	fmt.Fprintln(w, "| :---: | :--- | :---: | :---: |")

	for _, item := range diff.Items {
		name := fmt.Sprintf("`%s`", item.Identifier)
		switch item.Type {
		case stellar.DiffAdded:
			fmt.Fprintf(w, "| 🟢 ADDED | %s | — | %d%% |\n", name, item.NewPercentage)
		case stellar.DiffRemoved:
			fmt.Fprintf(w, "| 🔴 REMOVED | %s | %d%% | — |\n", name, item.OldPercentage)
		case stellar.DiffModified:
			fmt.Fprintf(w, "| 🟡 MODIFIED | %s | %d%% | %d%% |\n", name, item.OldPercentage, item.NewPercentage)
		case stellar.DiffUnchanged:
			fmt.Fprintf(w, "| ⚪ UNCHANGED | %s | %d%% | %d%% |\n", name, item.OldPercentage, item.OldPercentage)
		}
	}

	fmt.Fprintln(w, "\n**Net Change:**")
	fmt.Fprintf(w, "- 🟢 %d dependencies added\n", diff.AddedCount)
	fmt.Fprintf(w, "- 🔴 %d dependencies removed\n", diff.RemovedCount)
	fmt.Fprintf(w, "- 🟡 %d dependencies modified\n", diff.ModifiedCount)

	fmt.Fprintln(w, "\n---")
	fmt.Fprintln(w, "_Generated by [devex-cli](https://github.com/BCPathway/devex-cli) • Run `devex funding sync --network stellar` to apply._")
	fmt.Fprintln(w, "")
}

func statusToEmoji(status drips.VerificationStatus) string {
	switch status {
	case drips.StatusVerified:
		return "OK"
	case drips.StatusEscrow:
		return "🔒"
	case drips.StatusUnregistered:
		return "⬜"
	default:
		return "❓"
	}
}
