package cmd

import (
	"bytes"
	"strings"
	"testing"

	"github.com/BCPathway/devex-cli/pkg/drips"
)

func TestMarkdownFormatter_FormatInspect(t *testing.T) {
	formatter := &MarkdownFormatter{}
	var buf bytes.Buffer

	output := InspectOutput{
		TotalScanned: 48,
		Summary: InspectSummary{
			TotalSplitPct: 8,
		},
		Recipients: []drips.DripsRecipient{
			{
				DependencyName:      "github.com/stretchr/testify",
				Version:             "v1.8.4",
				Status:              drips.StatusVerified,
				RecommendedSplitPct: 5,
				Address:             "0x123",
			},
			{
				DependencyName:      "github.com/spf13/cobra",
				Version:             "v1.7.0",
				Status:              drips.StatusEscrow,
				RecommendedSplitPct: 3,
				Address:             "0x456",
			},
		},
	}

	err := formatter.Format(&buf, output)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	result := buf.String()

	// Verify Header
	if !strings.Contains(result, "**🔍 Drips Dependency Audit: 48 packages scanned. 8% total allocation.**") {
		t.Errorf("missing or incorrect header: %s", result)
	}

	// Verify Table Header
	if !strings.Contains(result, "| Dependency | Version | Status | Split % | Address |") {
		t.Errorf("missing table header: %s", result)
	}
	if !strings.Contains(result, "| :--- | :--- | :---: | :---: | :--- |") {
		t.Errorf("missing table alignment: %s", result)
	}

	// Verify Rows
	if !strings.Contains(result, "| `github.com/stretchr/testify` | `v1.8.4` | | 5% | `0x123` |") {
		t.Errorf("missing row 1: %s", result)
	}
	if !strings.Contains(result, "| `github.com/spf13/cobra` | `v1.7.0` | 🔒 | 3% | `0x456` |") {
		t.Errorf("missing row 2: %s", result)
	}

	// Verify Footer
	if !strings.Contains(result, "_Generated by [devex-cli]") {
		t.Errorf("missing footer: %s", result)
	}

	// Since items <= 10, should not contain details tag
	if strings.Contains(result, "<details>") {
		t.Errorf("should not contain <details> wrapper for %d items", len(output.Recipients))
	}
}

func TestMarkdownFormatter_FormatInspect_LargeList(t *testing.T) {
	formatter := &MarkdownFormatter{}
	var buf bytes.Buffer

	recipients := make([]drips.DripsRecipient, 15)
	for i := range recipients {
		recipients[i] = drips.DripsRecipient{
			DependencyName:      "pkg",
			Version:             "v1",
			Status:              drips.StatusUnregistered,
			RecommendedSplitPct: 0,
		}
	}

	output := InspectOutput{
		TotalScanned: 15,
		Recipients:   recipients,
	}

	err := formatter.Format(&buf, output)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	result := buf.String()

	// Since items > 10, should contain details tag
	if !strings.Contains(result, "<details><summary>View full dependency list</summary>") {
		t.Errorf("missing <details> wrapper for %d items", len(output.Recipients))
	}
}

func TestMarkdownFormatter_FormatDiff(t *testing.T) {
	formatter := &MarkdownFormatter{}
	var buf bytes.Buffer

	diff := &drips.SplitsDiff{
		ProjectID:     "123",
		ChainID:       1,
		AddedCount:    1,
		RemovedCount:  1,
		ModifiedCount: 1,
		Items: []drips.SplitDiffItem{
			{
				Identifier:    "pkg-added",
				Type:          drips.DiffAdded,
				NewPercentage: 3,
			},
			{
				Identifier:    "pkg-removed",
				Type:          drips.DiffRemoved,
				OldPercentage: 5,
			},
			{
				Identifier:    "pkg-modified",
				Type:          drips.DiffModified,
				OldPercentage: 2,
				NewPercentage: 4,
			},
		},
	}

	err := formatter.Format(&buf, diff)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	result := buf.String()

	// Verify Header
	if !strings.Contains(result, "**🔄 Drips Splits Diff: 3 changes proposed.**") {
		t.Errorf("missing or incorrect header: %s", result)
	}

	// Verify Table Header
	if !strings.Contains(result, "| Status | Dependency / Receiver | Old % | New % |") {
		t.Errorf("missing table header: %s", result)
	}

	// Verify Rows
	if !strings.Contains(result, "| 🟢 ADDED | `pkg-added` | — | 3% |") {
		t.Errorf("missing added row: %s", result)
	}
	if !strings.Contains(result, "| 🔴 REMOVED | `pkg-removed` | 5% | — |") {
		t.Errorf("missing removed row: %s", result)
	}
	if !strings.Contains(result, "| 🟡 MODIFIED | `pkg-modified` | 2% | 4% |") {
		t.Errorf("missing modified row: %s", result)
	}

	// Verify Net Change
	if !strings.Contains(result, "**Net Change:**") {
		t.Errorf("missing net change: %s", result)
	}
	if !strings.Contains(result, "- 🟢 1 dependencies added") {
		t.Errorf("missing net change added: %s", result)
	}
	if !strings.Contains(result, "- 🔴 1 dependencies removed") {
		t.Errorf("missing net change removed: %s", result)
	}
	if !strings.Contains(result, "- 🟡 1 dependencies modified") {
		t.Errorf("missing net change modified: %s", result)
	}
}
