package cmd

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/BCPathway/devex-cli/internal/config"
	"github.com/BCPathway/devex-cli/internal/logger"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialise a new .devex.yaml config in the current directory",
	Long: `Interactively creates a .devex.yaml configuration file in the
current working directory. Prompts for Drips Network settings,
project metadata, and dev-environment preferences.

If a .devex.yaml already exists, you will be asked to confirm
before overwriting.`,
	RunE: runInit,
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, args []string) error {
	const filename = ".devex.yaml"

	// Guard against accidental overwrites.
	if _, err := os.Stat(filename); err == nil {
		ok, promptErr := confirmOverwrite(filename)
		if promptErr != nil {
			return fmt.Errorf("reading confirmation: %w", promptErr)
		}
		if !ok {
			fmt.Println("Aborted.")
			return nil
		}
	}

	reader := bufio.NewReader(os.Stdin)

	fmt.Println("🚀  devex init — project configuration wizard")
	fmt.Println(strings.Repeat("─", 48))

	// --- Project metadata ---
	projectName := prompt(reader, "Project name", inferProjectName())
	repoURL := prompt(reader, "Repository URL (optional)", "")

	// --- Drips Network settings ---
	fmt.Println("\n📡  Drips Network Configuration")
	rpcEndpoint := prompt(reader, "RPC endpoint", "https://mainnet.optimism.io")
	chainIDStr := prompt(reader, "Chain ID", "10")
	walletAddress := prompt(reader, "Wallet address (optional)", "")

	// --- Stellar Network settings ---
	fmt.Println("\n🪐  Stellar Network Configuration")
	horizonURL := prompt(reader, "Horizon endpoint", "https://horizon-testnet.stellar.org")
	stellarAccountID := prompt(reader, "Stellar account ID (G... optional)", "")
	networkPassphrase := prompt(reader, "Network passphrase", "Test SDF Network ; September 2015")

	// --- Dev environment ---
	fmt.Println("\n🔧  Development Environment")
	devCmd := prompt(reader, "Dev start command", "docker compose up")

	chainID := 10
	if _, err := fmt.Sscanf(chainIDStr, "%d", &chainID); err != nil {
		logger.Warn("invalid chain ID %q, defaulting to 10", chainIDStr)
		chainID = 10
	}

	cfg := config.Config{
		Project: config.ProjectConfig{
			Name:          projectName,
			RepositoryURL: repoURL,
		},
		Drips: config.DripsConfig{
			RPCEndpoint:   rpcEndpoint,
			ChainID:       chainID,
			WalletAddress: walletAddress,
		},
		Stellar: config.StellarConfig{
			HorizonURL:        horizonURL,
			AccountID:         stellarAccountID,
			NetworkPassphrase: networkPassphrase,
		},
		Dev: config.DevConfig{
			StartCommand: devCmd,
		},
	}

	data, err := yaml.Marshal(&cfg)
	if err != nil {
		return fmt.Errorf("marshalling config: %w", err)
	}

	header := []byte("# DevEx CLI configuration — generated by 'devex init'\n# Docs: https://github.com/BCPathway/devex-cli#configuration\n\n")
	if err := os.WriteFile(filename, append(header, data...), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", filename, err)
	}

	fmt.Printf("\n✅  Created %s\n", filename)
	logger.Debug("wrote config: %+v", cfg)
	return nil
}

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

// prompt displays a labelled input prompt with an optional default value.
func prompt(r *bufio.Reader, label, defaultVal string) string {
	if defaultVal != "" {
		fmt.Printf("  %s [%s]: ", label, defaultVal)
	} else {
		fmt.Printf("  %s: ", label)
	}

	line, _ := r.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return defaultVal
	}
	return line
}

// confirmOverwrite asks the user whether to overwrite an existing file.
func confirmOverwrite(path string) (bool, error) {
	reader := bufio.NewReader(os.Stdin)
	fmt.Printf("⚠️  %s already exists. Overwrite? [y/N]: ", path)
	answer, err := reader.ReadString('\n')
	if err != nil {
		return false, err
	}
	answer = strings.TrimSpace(strings.ToLower(answer))
	return answer == "y" || answer == "yes", nil
}

// inferProjectName derives a default project name from the current directory.
func inferProjectName() string {
	dir, err := os.Getwd()
	if err != nil {
		return "my-project"
	}
	parts := strings.Split(strings.ReplaceAll(dir, "\\", "/"), "/")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return "my-project"
}
