package cmd

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/BCPathway/devex-cli/internal/config"
	"github.com/BCPathway/devex-cli/internal/logger"
	"github.com/BCPathway/devex-cli/internal/ui"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialise a new .devex.yaml config in the current directory",
	Long: `Interactively creates a .devex.yaml configuration file in the
current working directory. Prompts for Drips Network settings,
project metadata, and dev-environment preferences.

If a .devex.yaml already exists, you will be asked to confirm
before overwriting.`,
	RunE: runInit,
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, args []string) error {
	const filename = ".devex.yaml"

	// Guard against accidental overwrites.
	if _, err := os.Stat(filename); err == nil {
		ok, promptErr := ui.ConfirmOverwrite(filename)
		if promptErr != nil {
			return fmt.Errorf("reading confirmation: %w", promptErr)
		}
		if !ok {
			fmt.Println("Aborted.")
			return nil
		}
	}

	reader := bufio.NewReader(os.Stdin)

	fmt.Println("🚀  devex init — project configuration wizard")
	fmt.Println(strings.Repeat("─", 48))

	// --- Project metadata ---
	projectName := ui.Prompt(reader, "Project name", inferProjectName())
	repoURL := ui.Prompt(reader, "Repository URL (optional)", "")

	// --- Drips Network settings ---
	fmt.Println("\n📡  Drips Network Configuration")
	rpcEndpoint := ui.Prompt(reader, "RPC endpoint", "https://mainnet.optimism.io")
	chainIDStr := ui.Prompt(reader, "Chain ID", "10")
	walletAddress := ui.Prompt(reader, "Wallet address (optional)", "")

	// --- Stellar Network settings ---
	fmt.Println("\n🪐  Stellar Network Configuration")
	horizonURL := ui.Prompt(reader, "Horizon endpoint", "https://horizon-testnet.stellar.org")
	stellarAccountID := ui.Prompt(reader, "Stellar account ID (G... optional)", "")
	networkPassphrase := ui.Prompt(reader, "Network passphrase", "Test SDF Network ; September 2015")

	// --- Dev environment ---
	fmt.Println("\n🔧  Development Environment")
	devCmd := ui.Prompt(reader, "Dev start command", "docker compose up")

	chainID := 10
	if _, err := fmt.Sscanf(chainIDStr, "%d", &chainID); err != nil {
		logger.Warn("invalid chain ID %q, defaulting to 10", chainIDStr)
		chainID = 10
	}

	cfg := config.Config{
		Project: config.ProjectConfig{
			Name:          projectName,
			RepositoryURL: repoURL,
		},
		Drips: config.DripsConfig{
			RPCEndpoint:   rpcEndpoint,
			ChainID:       chainID,
			WalletAddress: walletAddress,
		},
		Stellar: config.StellarConfig{
			HorizonURL:        horizonURL,
			AccountID:         stellarAccountID,
			NetworkPassphrase: networkPassphrase,
		},
		Dev: config.DevConfig{
			StartCommand: devCmd,
		},
	}

	data, err := yaml.Marshal(&cfg)
	if err != nil {
		return fmt.Errorf("marshalling config: %w", err)
	}

	header := []byte("# DevEx CLI configuration — generated by 'devex init'\n# Docs: https://github.com/BCPathway/devex-cli#configuration\n\n")
	if err := os.WriteFile(filename, append(header, data...), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", filename, err)
	}

	fmt.Printf("\n✅  Created %s\n", filename)
	logger.Debug("wrote config: %+v", cfg)
	return nil
}

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

// inferProjectName derives a default project name from the current directory.
func inferProjectName() string {
	dir, err := os.Getwd()
	if err != nil {
		return "my-project"
	}
	parts := strings.Split(strings.ReplaceAll(dir, "\\", "/"), "/")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return "my-project"
}
